apiVersion: v1
kind: Service
metadata:
  name: rexray-server
  labels:
    app: rexray-server
  annotations:
    avi_proxy: '{"virtualservice": {"auto_allocate_ip": true, "east_west_placement": false}}'
spec:
  clusterIP: None
  ports:
    - port: 7979
  selector:
    app: rexray-server
