apiVersion: v1
kind: ReplicationController
metadata:
  name: redis01-master
  labels:
    app: redis01
    role: master
spec:
  replicas: 1
  selector:
    app: redis01
    role: master
  template:
    metadata:
      labels:
        app: redis01
        role: master
    spec: 
      containers:
      - name: redis01-master
        image: redis
        ports:
        - containerPort: 6379
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          timeoutSeconds: 1
