apiVersion: v1
kind: Service
metadata:
  name: opscenter
  labels:
    app: opscenter
  annotations:
    avi_proxy: '{"virtualservice": {"auto_allocate_ip": true, "east_west_placement": false}}'
spec:
  clusterIP: None
  ports:
  - name: web
    port: 8888 
    targetPort: 8888
  - name: job-tracker
    port: 50031
  - name: monitoring
    port: 61620 
  selector:
    app: opscenter
