apiVersion: v1
kind: ReplicationController
metadata:
  name: iperf
  labels:
    app: iperf
spec:
  replicas: 1
  selector:
    app: iperf
  template:
    metadata:
      labels:
        app: iperf
    spec: 
      containers:
      - name: iperf
        image: networkstatic/iperf3 
        command: ["iperf3","-s"]
        ports:
        - containerPort: 5201
