apiVersion: v1
kind: Service
metadata:
  name: iperf
  labels:
    app: iperf
  annotations:
    avi_proxy: '{"pool": {"health_monitor_refs": []}, "virtualservice": {"auto_allocate_ip": true, "east_west_placement": false}}'
spec:
  clusterIP: None
  ports:
  - port: 5201
  selector:
    app: iperf
