apiVersion: v1
kind: Service
metadata:
  name: graphite
  labels:
    app: graphite
  annotations:
    avi_proxy: '{"virtualservice": {"auto_allocate_ip": true, "east_west_placement": false}}'
spec:
  clusterIP: None
  ports:
  - name: graphite-web
    port: 80
  - name: graphite-client
    port: 2003
  selector:
    app: graphite
