apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
  annotations:
    avi_proxy: '{"virtualservice": {"auto_allocate_ip": true, "east_west_placement": false}}'
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: grafana
